title: Linguly Docs
description: >- # this means to ignore newlines until "baseurl:"
  Linguly, an open source language learning platform
theme: just-the-docs

url: https://docs.linguly.io
github_username:  linguly
twitter_username: linguly
instagram_username: linguly_io

repository: Linguly/docs # for github-metadata

aux_links:
  About Linguly: https://github.com/Linguly

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# assets
logo: "/assets/images/linguly.png"
favicon_ico: "/assets/images/favicon.ico"

# External navigation links
nav_external_links:
  - title: Linguly on GitHub
    url: https://github.com/Linguly
    opens_in_new_tab: true 


plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

# Footer configuration
footer_content: "Copyright &copy; 2025 Linguly. Distributed by an <a href=\"https://github.com/Linguly/docs/blob/main/LICENSE\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/Linguly/docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from